In [6]:
# ## To use np.load, downgrade numpy version
# !pip uninstall numpy --y
# !pip install --upgrade numpy==1.16.1

## Executable notebook

- CS410 Final Project
- members : Changsoo Kim, Hongseok Ha
- updated : 2020/12/05

In [7]:
import numpy as np
from importlib import reload
# import lda
print(np.__version__)


1.16.1


### 0. References

- Code and Dataset from a homepage of the original author : http://sifaka.cs.uiuc.edu/~wang296/
- Python code (Especially for data preparation, before LDA) : https://github.com/tonyzhang1231/LARA_Python

### 1. Creating Corpus and Vocabs

- stopwords >> nltk package
- Review Contents >> Parsing sentences & Computing frequencies (using nltk FreqDist)
- Output : yelp_mp1_corpus.npy

In [1]:
from src.CreateVocab import *
from src.Structure import *
from src.lda_preproc import *

In [14]:
# cv_obj = CreateVocab()  # create an instance
# cv_obj.create_stopwords()  # create a list of stopwords

In [17]:
# suffix = "json"
# folder = "./data/yelp mp1 data/"
# cv_obj.read_data(folder, suffix)
# cv_obj.create_vocab()

# # save it to a file
# savefilepath = "./data/yelp_mp1_corpus"
# cv_obj.save_to_file(savefilepath)

loading file No.1
loading file No.2
loading file No.3
loading file No.4
loading file No.5
loading file No.6
loading file No.7
loading file No.8
loading file No.9
loading file No.10
loading file No.11
loading file No.12
loading file No.13
loading file No.14
loading file No.15
loading file No.16
loading file No.17
loading file No.18
loading file No.19
loading file No.20
loading file No.21
loading file No.22
loading file No.23
loading file No.24
loading file No.25
loading file No.26
loading file No.27
succeed saving to file ./data/yelp_mp1_corpus


### 2. Assigning Corpus to a variable

In [2]:
cv_obj = CreateVocab()
loadfilepath = "./data/yelp_mp1_corpus.npy"

## load from yelp_mpl_corpus.npy 
(cv_obj.corpus, cv_obj.Vocab, cv_obj.Count, cv_obj.VocabDict) = np.load(loadfilepath)

In [3]:
# check the data
print(cv_obj.Vocab[:10])
print(cv_obj.Count[:10])

["'50", "'best", "'bruschetta", "'burb", "'caus", "'chef", "'chicken", "'corn", "'cue", "'do"]
[6, 14, 6, 11, 39, 6, 36, 48, 6, 10]


In [4]:
## Warning : takes more than 15 minutes ##
data = Corpus(cv_obj.corpus, cv_obj.Vocab, cv_obj.Count, cv_obj.VocabDict)

### 3. Using LDA to find latent topics

- Child of Corpus class, LDA_utils class
- Input : Corpus
- Output : LDA outputs

In [13]:
import sys, importlib
importlib.reload(sys.modules['src.lda_preproc'])
from src.lda_preproc import LDA_utils

In [5]:
## To make a doc-term matrix

data_lda = LDA_utils(data)
print(data_lda.num_reviews_tot)
print(data_lda.doc_term_matrix.shape)

Restaurant 7lnOgOMd7zys3bFfWY_jIw Done!
Restaurant 0qnMSq3gYhGDesZKxNgAkQ Done!
Restaurant 8d-RAa59tgV06VRa5SOe9A Done!
Restaurant 8y00IHK9sbA1Zhl2E9hmpA Done!
Restaurant A9xPHLcWtRgK6Mf4-ksBrw Done!
Restaurant 9N0YqwhE1qwU4OmhzwGjtA Done!
Restaurant 8y00IHK9sbA1Zhl2E9hmpA Done!
Restaurant d5YWKrP-zG74nqOYzHn7Zg Done!
Restaurant 8d-RAa59tgV06VRa5SOe9A Done!
Restaurant 7pezxyAK-7l5Yfr7W7fFQQ Done!
Restaurant b7jDtbG7UloYasZ9sVXHWg Done!
Restaurant 4lgk5AJvmoXPrfSlCyjiQg Done!
Restaurant 0qnMSq3gYhGDesZKxNgAkQ Done!
Restaurant 7lnOgOMd7zys3bFfWY_jIw Done!
Restaurant 9GVazUhx0dYB-_H0hlgB5w Done!
Restaurant 3OLZOlqgOXdqY0uwxcOTfw Done!
Restaurant CvmAN25laBbwZTqmlEAR1Q Done!
Restaurant b7jDtbG7UloYasZ9sVXHWg Done!
Restaurant 3VCZ21-DIw7voVexDMXDSA Done!
Restaurant 7pezxyAK-7l5Yfr7W7fFQQ Done!
Restaurant aq_UTxlYvMNEN-urxbUddA Done!
Restaurant 9GVazUhx0dYB-_H0hlgB5w Done!
Restaurant 9N0YqwhE1qwU4OmhzwGjtA Done!
Restaurant 9IRdWhDNo2T6vyMLwrQdMw Done!
Restaurant 3VCZ21-DIw7voVexDMXDSA Done!


In [8]:
### Checking all-zero rows
np.where(~data_lda.doc_term_matrix.any(axis=1))[0]

array([ 5601, 10195, 17492, 19825, 25420, 25657, 29272, 30485, 32744,
       36314, 38970, 39207, 46593])

In [9]:
## LDA Model Fitting
## takes more than 5 minutes to train
## Using lda package

data_lda.model_fit(n_topics = 10, n_iter = 1500, random_state = 1)

INFO:lda:n_documents: 48079
INFO:lda:vocab_size: 12311
INFO:lda:n_words: 3221134
INFO:lda:n_topics: 10
INFO:lda:n_iter: 1500
INFO:lda:<0> log likelihood: -32111304
INFO:lda:<10> log likelihood: -27752659
INFO:lda:<20> log likelihood: -26041166
INFO:lda:<30> log likelihood: -25479626
INFO:lda:<40> log likelihood: -25231025
INFO:lda:<50> log likelihood: -25088022
INFO:lda:<60> log likelihood: -25011676
INFO:lda:<70> log likelihood: -24967390
INFO:lda:<80> log likelihood: -24925254
INFO:lda:<90> log likelihood: -24896038
INFO:lda:<100> log likelihood: -24871857
INFO:lda:<110> log likelihood: -24849649
INFO:lda:<120> log likelihood: -24835875
INFO:lda:<130> log likelihood: -24823937
INFO:lda:<140> log likelihood: -24811676
INFO:lda:<150> log likelihood: -24803809
INFO:lda:<160> log likelihood: -24794110
INFO:lda:<170> log likelihood: -24788604
INFO:lda:<180> log likelihood: -24784119
INFO:lda:<190> log likelihood: -24775157
INFO:lda:<200> log likelihood: -24764076
INFO:lda:<210> log likeli

In [10]:
## doc_topic matrix
## doc = review, doc consists of multiple sentences
## words can be substituted, by using data.Vocabdict (implemented in create_doc_term_matrix)

print(data_lda.model.doc_topic_.shape)
print(data_lda.model.doc_topic_[0, :])  ## first document >> topic 2

(48079, 10)
[0.00434783 0.00434783 0.87391304 0.00434783 0.00434783 0.09130435
 0.00434783 0.00434783 0.00434783 0.00434783]


In [11]:
## Describe topics (top 10 words)

data_lda.describe_topics(10)

Topic 0: waistlin lobstah role n'chees pla oy steadili goo gestur measur
Topic 1: n'chees urth ordeal foo waistlin tabasco tim gestur worthwhil lightweight
Topic 2: pastor- sandwhich n'chees goo lane delet cantanker lightweight besid pla
Topic 3: tha foo disgustingli n'chees goo pla restaraunt besid ordeal ribs.th
Topic 4: goo pla bbblt n'chees doesnt chica hostil brisk cheerwin ri
Topic 5: foo goo breaker eg n'chees chick pla ordeal gnosh to.th
Topic 6: tackl goo stapl pla n'chees bife gestur foo drill greasiest
Topic 7: chocohol despit hostil goo n'chees cheerwin ordeal dumpi ongo lightweight
Topic 8: fret chick goo n'chees cocain pore wine/b lightweight pla saturday
Topic 9: foo pla greasiest goo server/bartend gnosh n'chees restaraunt gestur tim


In [14]:
## Key matrices
print("Doc-term matrix Shape : {0}".format(data_lda.doc_term_matrix.shape))
print("Doc-topic matrix Shape : {0}".format(data_lda.model.doc_topic_.shape))
print("topic-word matrix Shape : {0}".format(data_lda.model.components_.shape))

Doc-term matrix Shape : (48079, 12311)
Doc-topic matrix Shape : (48079, 10)
topic-word matrix Shape : (10, 12311)


In [ ]:
## data_lda.describe_single_doc(0)
## data_lda.describe_multiple_doc(0, 10)

### 3-2. Calculate inner-topic similarity

1. Topic Coherence : Given a topic k, the PMI score is calculated by the following equation :
2. N : number of the most probable words in this topic (default = 20?)

$$ C_K = \frac{2}{N(N-1)} \sum_{1\le i<j \le N}log \frac{p(w_i, w_j)}{p(w_i)p(w_j)}$$ 

--- STILL IMPLEMENTING

In [15]:
## Num of Topics * Num of Words >> Topic distribution
print(data_lda.model.components_.shape )

(10, 12311)


In [16]:
sum((data_lda.doc_term_matrix[:, 11823] > 0) & (data_lda.doc_term_matrix[:, 6580] > 0))

1044

In [18]:
# n_topics = 10
# for topic_idx in range(len(n_topics)):
#     all_word_cnts = sum(sum(data_lda.doc_term_matrix > 0))
#     words_now_idx = top_k_inds[topic_idx,:]
#     for i in word_now_idx:

### 3-3. KL divergence

1. LARAM 논문에서는 trip advisior에서 제공하는 7개의 aspects를 Bootstrapping으로 확장하여 LDA를 적용. 
2. 1을 ground-truth로 가정하고 방법론들 간 성능을 비교 하였음 
3. 논문 구현이 목적이고 topic modeling에 LDA를 사용 하였으므로, KL-divergence는 skip

# Codes Below are not used ----------------------------------------------------

# -----------------------------------------------------------------------------------

### 2. (Previous) Using Bootstrap method

In [3]:
# step 2. using bootstrapping method
# if loading data from saved files
cv_obj = CreateVocab()
loadfilepath = "./data/yelp_mp1_corpus.npy"

## yelp_mpl_corpus.npy 파일에 저장한 변수들을 그대로 불러 옴.
(cv_obj.corpus, cv_obj.Vocab, cv_obj.Count, cv_obj.VocabDict) = np.load(loadfilepath)

In [4]:
# cv_obj.corpus[0]
print(cv_obj.Vocab[:10])
print(cv_obj.Count[:10])

["'50", "'best", "'bruschetta", "'burb", "'caus", "'chef", "'chicken", "'corn", "'cue", "'do"]
[6, 14, 6, 11, 39, 6, 36, 48, 6, 10]


In [5]:
# data = Corpus(cv_obj.corpus, cv_obj.Vocab, cv_obj.Count,cv_obj.VocabDict)
# load_Aspect_Terms(BSanalyzer,loadfilepath,VocabDict)

# otherwise
## structure.py 에 포함된 Corpus class
## 변수 저장
data = Corpus(cv_obj.corpus, cv_obj.Vocab, cv_obj.Count, cv_obj.VocabDict) 

### 3. 아래 Bootstrapping 파트를 LDA로 갈아 끼우면 LARAM 과 유사하게 동작

In [16]:
print(data.Vocab[:4])
print(data.VocabTF[:4])

["'50", "'best", "'bruschetta", "'burb"]
[6, 14, 6, 11]


In [17]:
print(len(data.Restaurants))
print(data.Restaurants[0].RestaurantID)
print(data.Restaurants[0].Name)
print(data.Restaurants[0].Price)
print(len(data.Restaurants[0].Reviews))
print(data.Restaurants[0].NumOfReviews)


##Review에서 stn(content를 문장, 단어로 tokenize 하는 함수인 parse_to_sentence_UseVocab)
print(data.Restaurants[0].Reviews[0].Stns[0].stn)
print(data.Restaurants[0].Reviews[0].Stns[0].unilength)
print(data.Restaurants[0].Reviews[0].Stns[0].label)
print(data.Restaurants[0].Reviews[0].NumOfUniWord)

27
7lnOgOMd7zys3bFfWY_jIw
Langer’s
$$
2171
2171
<FreqDist with 6 samples and 6 outcomes>
6
[4]
21


### 코드 실행 계속

In [8]:
## structure.py 의 Bootstrapping class
BSanalyzer = Bootstrapping() 

In [9]:
loadfilepath = "./init_aspect_word.txt"
load_Aspect_Terms(BSanalyzer, loadfilepath, cv_obj.VocabDict)

Aspect Keywords loading completed


In [10]:
### Aspect Words
f = open(loadfilepath, "r")
for l in f:
    print(l)

recommend, price, quality, worth, food 

service, minute, wait, staff, order

location, park, atmosphere, place, room

pork, chicken, beef, rib

shrimp, oyster, egg, sauce, bread


In [11]:
print(data.VocabDict['recommend'])
print(data.VocabDict['price'])
print(data.VocabDict['qualiti'])  ## stemming 한 뒤의 결과이기 때문에 qualiti 가 됨.

9032
8684
8861


In [15]:
## aspect words에 대한 frequencies가 VocabDict의 value이므로,, load_Aspect_Term 함수에서 해당 값을 가져옴
BSanalyzer.Aspect_Terms

[[9032,
  8684,
  8861,
  12137,
  4530,
  5447,
  10971,
  8577,
  9004,
  4975,
  4663,
  8058,
  8677,
  1422,
  8998,
  9171,
  9261,
  7519,
  8693,
  5614,
  10450,
  9955,
  7506,
  3272,
  2685,
  6641,
  936,
  3147,
  10002,
  9881,
  7985,
  11843,
  436,
  3103,
  11665],
 [9737,
  7153,
  11824,
  10356,
  7904,
  10765,
  5582,
  4671,
  6610,
  9659,
  11606,
  11099,
  6538,
  11160,
  11832,
  9735,
  5569,
  1204,
  1251,
  11188,
  1170,
  491,
  8989,
  11838,
  4398,
  8152,
  7123,
  1164,
  2133,
  9532,
  10799,
  1589,
  5390,
  7877,
  4860],
 [6584,
  8137,
  1237,
  8434,
  9357,
  10507,
  8054,
  6638,
  12036,
  11637,
  6661,
  1722,
  781,
  4736,
  3174,
  6726,
  4378,
  11290,
  623,
  6567,
  9504,
  9349,
  2377,
  6720,
  4952,
  6324,
  5671,
  6363,
  2410,
  3285,
  2172,
  7412,
  3508,
  8576,
  3592],
 [8563,
  2418,
  1523,
  9255,
  11812,
  2887,
  1562,
  8819,
  9457,
  6006,
  1934,
  2373,
  10933,
  1862,
  9843,
  6647,
  6146,
  10

In [13]:
# expand aspect keywords >> 어떻게 확장하나??
## Bootstrapping class의 sentence_label() 함수 : 
Add_Aspect_Keywords(BSanalyzer, 5, 5, data)

savefilepath = './output/final_aspect_words.txt'
save_Aspect_Keywords_to_file(BSanalyzer, savefilepath, cv_obj.Vocab)

/Users/sktelecom/Desktop/LARAM/Ref/LARA_Python/src/Structure.py:137: RuntimeWarning: invalid value encountered in double_scalars
  return N * (A * D - B * C) * (A * D - B * C) / aDF / (B + D) / tDF / (C + D)


complete iteration 1/5
complete iteration 2/5
complete iteration 3/5
complete iteration 4/5
complete iteration 5/5


In [18]:
### Aspect Words (Expanded)
f = open(savefilepath, "r")
for l in f:
    print(l)

recommend, price, qualiti, worth, food, highli, thai, portion, reason, good, fri, pad, pretti, bar, realli, reserv, rice, next, pricey, huge, sticki, size, network, deMcsrch.finit, cole, lotu, allig, damn, slice, siam, overal, walk, 30, curri, vega, 



servic, minut, wait, staff, order, tabl, hour, friendli, long, seat, us, time, line, told, waiter, server, hostess, ask, attent, took, arriv, 45, readi, waitress, first, parti, min, around, call, sat, take, best, help, open, get, 



locat, park, atmospher, place, room, street, pack, lot, wicker, valid, love, block, across, fun, date, macarthur, find, trendi, 7th, live, sandwich, romant, chees, mac, goat, la, hype, langer, chicago, deli, canter, n, dish, portillo, dog, 



pork, chicken, beef, rib, waffl, corn, belli, pull, sage, italian, brisket, cheek, tender, brais, short, loui, juici, st., taco, kobe, dri, flavor, fish, pastor, snapper, al, slider, meat, de, moist, panza, red, shoulder, tostada, 



shrimp, oyster, egg, sauc, bread,

In [39]:
print(data.Restaurants[0].Reviews[0].UniWord)
print(data.Restaurants[0].Reviews[0].W.shape) ## 5개 aspects * 21개 words

[  303   734  1509  1876  2377  2685  3292  3790  5360  6538  6766  7840
  8181  8434  8993  9992 10002 10735 11387 11897 12017]
(5, 21)


In [43]:
print(data.Restaurants[0].Reviews[0].W[4])  ## 이 리뷰는 4번 topic에 대한 점수만 가지고 있음..

[0.04545455 0.04545455 0.04545455 0.04545455 0.04545455 0.04545455
 0.04545455 0.04545455 0.04545455 0.04545455 0.04545455 0.04545455
 0.09090909 0.04545455 0.04545455 0.04545455 0.04545455 0.04545455
 0.04545455 0.04545455 0.04545455]


In [50]:
print(data.Restaurants[0].Reviews[0].num_stn_aspect_word)
## 이건 언제 계산되었나? collect_stat_for_each_review 에서 계산됨


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([  303,   734,  1509,  1876,  2377,  2685,  3292,  3790,  5360,
        6538,  6766,  7840,  8181,  8434,  8993,  9992, 10002, 10735,
       11387, 11897, 12017])

In [19]:
create_all_W(BSanalyzer, data)
W_outputfolderpath = "./output/"
produce_data_for_rating(BSanalyzer, data, W_outputfolderpath)

print_summary_stats(data)

Creating W matrix for Restaurant 1
Creating W matrix for Restaurant 2
Creating W matrix for Restaurant 3
Creating W matrix for Restaurant 4
Creating W matrix for Restaurant 5
Creating W matrix for Restaurant 6
Creating W matrix for Restaurant 7
Creating W matrix for Restaurant 8
Creating W matrix for Restaurant 9
Creating W matrix for Restaurant 10
Creating W matrix for Restaurant 11
Creating W matrix for Restaurant 12
Creating W matrix for Restaurant 13
Creating W matrix for Restaurant 14
Creating W matrix for Restaurant 15
Creating W matrix for Restaurant 16
Creating W matrix for Restaurant 17
Creating W matrix for Restaurant 18
Creating W matrix for Restaurant 19
Creating W matrix for Restaurant 20
Creating W matrix for Restaurant 21
Creating W matrix for Restaurant 22
Creating W matrix for Restaurant 23
Creating W matrix for Restaurant 24
Creating W matrix for Restaurant 25
Creating W matrix for Restaurant 26
Creating W matrix for Restaurant 27
TotalNumOfRest =27

TotalNumOfReviews

In [58]:
print(data.all_num_stn_word.shape) ##12,311 단어들
print(data.all_num_stn_aspect_word.shape) ## aspect * words

(12311,)
(5, 12311)


In [62]:
data.Restaurants[0].Reviews[0].num_stn_word  ## 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [65]:
data.Restaurants[0].Reviews[0].Stns[0].stn

FreqDist({7840: 1, 8993: 1, 8181: 1, 11897: 1, 6766: 1, 303: 1})

### Applying LDA -------------------------------------

In [ ]:
## doc-term matrix
## doc은 1개의 review. multiple sentences 로 구성됨. 
## 단어는 data.VocabDict에서 숫자로 치환할 수 있음

In [250]:
# print(data.NumOfRestaurants)
# print(data.Restaurants[0].NumOfReviews)

27
2171


In [253]:
# num_reviews_tot = 0
# for rest in (data.Restaurants):
#     num_reviews_tot += rest.NumOfReviews
# print(num_reviews_tot)

In [255]:
# def create_doc_term_matrix(corpus):
#     doc_term_tmp = np.zeros((num_reviews_tot, len(vocab_lda)))
#     i = 0
#     for rest in corpus.Restaurants:       
#         for review in rest.Reviews:
#             for stn in review.Stns:
#     #             print(stn.stn)
#                 for key in stn.stn:
#                     value = stn.stn[key]
#     #                 print(key)
#                     doc_term_tmp[i][key-1] += value
#     #                 if i % 100 == 0 :
#     #                     print(i)
#             i += 1
#     return doc_term_tmp

In [258]:
# doc_term = np.zeros((num_reviews_tot, len(vocab_lda)))
# doc_term.shape

(48079, 12311)

In [259]:
# test = create_doc_term_matrix(data)

In [260]:
# test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [261]:
# print(sum(test[0] != 0))
# print(sum(test[1] != 0))
# print(sum(test[2] != 0))
# print(sum(sum(test != 0)))

21
22
145
2636481


In [263]:
# print(test.shape)
# test_int = test.astype(int)

(48079, 12311)


In [264]:
# model = lda.LDA(n_topics=20, n_iter=1500, random_state=1)

In [265]:
# model.fit(test_int)  # model.fit_transform(X) is also available

INFO:lda:n_documents: 48079
INFO:lda:vocab_size: 12311
INFO:lda:n_words: 3221134
INFO:lda:n_topics: 20
INFO:lda:n_iter: 1500
INFO:lda:<0> log likelihood: -35301802
INFO:lda:<10> log likelihood: -28582158
INFO:lda:<20> log likelihood: -26795784
INFO:lda:<30> log likelihood: -26149864
INFO:lda:<40> log likelihood: -25828209
INFO:lda:<50> log likelihood: -25644433
INFO:lda:<60> log likelihood: -25531822
INFO:lda:<70> log likelihood: -25457416
INFO:lda:<80> log likelihood: -25396193
INFO:lda:<90> log likelihood: -25360910
INFO:lda:<100> log likelihood: -25331652
INFO:lda:<110> log likelihood: -25307320
INFO:lda:<120> log likelihood: -25283951
INFO:lda:<130> log likelihood: -25273614
INFO:lda:<140> log likelihood: -25260131
INFO:lda:<150> log likelihood: -25248366
INFO:lda:<160> log likelihood: -25243735
INFO:lda:<170> log likelihood: -25230737
INFO:lda:<180> log likelihood: -25235502
INFO:lda:<190> log likelihood: -25219682
INFO:lda:<200> log likelihood: -25218154
INFO:lda:<210> log likeli

In [266]:
# topic_word = model.topic_word_  # model.components_ also works
# n_top_words = 8
# for i, topic_dist in enumerate(topic_word):
#     topic_words = np.array(vocab_lda)[np.argsort(topic_dist)][:-(n_top_words+1):-1]
#     print('Topic {}: {}'.format(i, ' '.join(topic_words)))

Topic 0: lobstah role oy waistlin pla nephew goo buttah
Topic 1: cocain pore goo fret greasiest alli nevertheless foo
Topic 2: urth waistlin tabasco n'chees ordeal minuscul foo tim
Topic 3: tha foo disgustingli besid restaraunt pla current veg
Topic 4: ongo soundtrack dumpi goo fremont cheerwin disgustingli socal
Topic 5: chocohol hostil despit goo n'chees dinki ordeal cheerwin
Topic 6: cantanker delet sandwhich soundtrack goo pla balk n'chees
Topic 7: doesnt hostil chica pla bee fret goo porter
Topic 8: chick foo portillo waffel gnosh harvest hug pla
Topic 9: bbblt brisk ri goo pla cheerwin sickli pore
Topic 10: n'chees lightweight once.i knockout saw eastsid revers 'que
Topic 11: chick wine/b saturday fret goo ordeal n'chees crisi
Topic 12: steadili waistlin greasiest measur pla byo-win n'chees windshield
Topic 13: foo greasiest pla goo server/bartend restaraunt drill lovabl
Topic 14: tackl stapl bife goo drill pla greasiest n'chees
Topic 15: n'chees goo lightweight foo pla realiz .-

In [267]:
# doc_topic = model.doc_topic_

In [268]:
# doc_topic.shape

(48079, 20)

In [269]:
# doc_topic[0].argmax()

18

In [276]:
# data.Restaurants[0].Reviews[0].Stns[0].stn

FreqDist({7840: 1, 8993: 1, 8181: 1, 11897: 1, 6766: 1, 303: 1})

In [277]:
# for word, val in data.VocabDict.items(): #mydict에 아이템을 하나씩 접근해서, key, value를 각각 name, age에 저장
#     if val in [7840, 8993, 8181, 11897, 6766, 303]:
#         print(word)

pastrami
real
way
19
make
one


### 아래는 이해를 돕기 위한 예제 ----

In [186]:
data.Restaurants[0].Reviews[0].Stns[0].stn.values()

dict_values([1, 1, 1, 1, 1, 1])

In [170]:
type(data.Restaurants[0].Reviews[0].Stns[0].stn)

nltk.probability.FreqDist

In [190]:
data.Restaurants[0].Reviews[0].Stns[0].stn.values

<function FreqDist.values>

In [192]:
for key in data.Restaurants[0].Reviews[0].Stns[0].stn:
    print(key)
    print(data.Restaurants[0].Reviews[0].Stns[0].stn[key])

7840
1
8993
1
8181
1
11897
1
6766
1
303
1


In [187]:
for values in data.Restaurants[0].Reviews[0].Stns[0].stn.values():
    print(values)

1
1
1
1
1
1


In [126]:
data.Restaurants[0].Reviews[0].Stns[0].stn

1

In [108]:
print(data.Restaurants[0].Reviews[0].ReviewID)

m4G-dbXxrF6pzEuIj7vZpw


In [91]:
print(data.Restaurants[0].Reviews[0].Stns[0].stn)
print(data.Restaurants[0].Reviews[0].Stns[0].unilength)

<FreqDist with 6 samples and 6 outcomes>
6


In [116]:
print(data.VocabDict.get('real'))
print(data.VocabDict.get('MVPs'))
print(data.VocabDict.get('pastrami'))

8993
None
8181


In [120]:
for word, val in data.VocabDict.items(): #mydict에 아이템을 하나씩 접근해서, key, value를 각각 name, age에 저장
    if val in [7840, 8993, 8181, 11897, 6766, 303]:
        print(word)

pastrami
real
way
19
make
one


### 예제 END ----